###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'master'
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint Code Base

    runs-on: self-hosted

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
      
      - name: run python check
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip -q install pathspec

      - name: check sudo 
        run: |
          sudo mount
          echo "------------lsblk-------------"
          sudo lsblk

      - name: check free space 
        run: |
          df -h
          echo "----pwd-----"
          pwd
      - name: check error
        run: |
          exit 1
